#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            60

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    565679
berryc text_unfocus_color  FFCB6B

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"
berryc decorate_new "true"

xrandr --output Virtual1 --mode 1920x1080
~/.config/polybar/launch.sh --grayblocks
nitrogen --restore
picom 

